### ISSUE TITLE
Stream RegEx not broad enough

### ISSUE THREAD

**Issue by SD-Miles** [seanthegeek/graylog-fortigate-syslog#9]
As of this writing, the stream in this content pack matches FortiGate serial numbers based on the regular expression `^FG([0-9]{2,3})[A-Z]T|^FGT`. Without giving away the serial number, I have a FortiGate with a serial which follows this pattern:

- FG, digit, H, digit, letter, T, letter,  eight digits

I revised the RegEx in my deployment to `^FG([0-9]{2,3}[A-Z]T|[A-Z0-9]+)` and this works for me. But I am not a RegEx expert (or even fluent) and I don't know the full spectrum of possible FortiGate serials, so please consider it just a starting point for revision.

**Comment by DarNattp** [comment]
please show example for fortigate log
